"we can use vim-plug to replace Vundle!!
"set nocompatible              " be iMproved, required
"filetype off                  " required

" Vundle setting
let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
  echo "Installing Vundle.."
  echo ""
  silent !mkdir -p ~/.vim/bundle
  silent !git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/vundle
  let iCanHazVundle=0
endif
filetype off                  " required

if iCanHazVundle == 0
  " first-time setup, run PluginInstall automatically
  autocmd VimEnter * PluginInstall
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" ========== Plugin Setting ==========
Plugin 'lifepillar/vim-solarized8'
if empty(globpath(&runtimepath, 'colors/solarized8_flat.vim'))
  echohl ErrorMsg
  echom "Missing colorscheme solarized8_flat. Try running: vim -Nu ~/.vimrc -n '+PluginInstall' '+qall'"
  echohl None
endif
colorscheme solarized8_flat

Plugin 'itchyny/lightline.vim'
let g:lightline = {
      \ 'colorscheme': 'PaperColor',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'modified', 'filename' ] ],
      \ },
      \ 'mode_map': {
        \ 'n' : 'N',
        \ 'i' : 'I',
        \ 'R' : 'R',
        \ 'v' : 'V',
        \ 'V' : 'VL',
        \ "\<C-v>": 'VB',
        \ 'c' : 'C',
        \ 's' : 'S',
        \ 'S' : 'SL',
        \ "\<C-s>": 'SB',
        \ 't': 'T',
        \ },
      \ }
"Plugin 'airblade/vim-gitgutter'
" Tagbar is useful for symbol outlines in C/C++/Python/asm, but not for Scala in
" this setup because the ctags path here does not cover Scala well.
"Plugin 'majutsushi/tagbar'
"Plugin 'mbbill/undotree'
"Plugin 'scrooloose/nerdtree' "nerdtree can somewhat be replaced by :h netrw
"Plugin 'vim-airline/vim-airline' "can be replaced by customized :h statusline

"Plugin 'dhruvasagar/vim-table-mode' "draw a good table
"Plugin 'hari-rangarajan/cctree'  "call tree, maybe YCM is sufficient
"Plugin 'mileszs/ack.vim'  "replace ack.vim by setting :h grepprg
"Plugin 'scrooloose/nerdcommenter'  "multi line comment tool
"Plugin 'SirVer/ultisnips'  "snippet driver, we can use vim-snippets with it.

filetype plugin indent on
" ========== Plugin Setting End ==========

set listchars=tab:>-,trail:-
" Another way to show hidden characters by highlighting tabs and spaces directly.
" highlight ShowSpaceChar guifg=Yellow ctermfg=Yellow
" match ShowSpaceChar /\t\| /
" Use true color if supported, otherwise fall back to 256 colors
if exists('+termguicolors') && (has('nvim') || &term =~ 'xterm\|screen\|tmux')
  set termguicolors
else
  set t_Co=256
endif
set background=dark
set guifont=monospace\ 12

set backspace=indent,eol,start

" Default to 4-space indentation, then adapt per file when existing style is clear.
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent

function! s:UseDefaultIndent() abort
  setlocal tabstop=4
  setlocal softtabstop=4
  setlocal shiftwidth=4
  setlocal expandtab
endfunction

function! s:DetectIndentStyle() abort
  let l:tabs = 0
  let l:spaces = []

  for l:num in range(1, min([line('$'), 250]))
    let l:line = getline(l:num)
    if l:line =~# '^\t'
      let l:tabs += 1
    elseif l:line =~# '^  \+[^ ]'
      call add(l:spaces, strlen(matchstr(l:line, '^ \+')))
    endif
  endfor

  if l:tabs > len(l:spaces)
    setlocal noexpandtab
    setlocal tabstop=4
    setlocal softtabstop=0
    setlocal shiftwidth=4
    return
  endif

  if empty(l:spaces)
    call s:UseDefaultIndent()
    return
  endif

  let l:width = 4
  if !empty(filter(copy(l:spaces), 'v:val % 2 == 0 && v:val % 4 != 0'))
    let l:width = 2
  endif

  execute 'setlocal tabstop=' . l:width
  execute 'setlocal softtabstop=' . l:width
  execute 'setlocal shiftwidth=' . l:width
  setlocal expandtab
endfunction

augroup user_indent_style
  autocmd!
  autocmd BufNewFile * call s:UseDefaultIndent()
  autocmd BufReadPost,FileType * call s:DetectIndentStyle()
augroup END

" Show uncompleted command in the status line
set showcmd
set history=100

" Keep a statusline available if needed, though the filename is already shown on the tabline.
" set laststatus=2
set updatetime=250

" Allow many tab pages, but this does not control how the tabline is rendered.
set tabpagemax=100

set wrap
set linebreak

set matchpairs+=<:>
if has('clipboard')
  set clipboard=unnamedplus
endif
set mouse=n
set splitbelow

" Insert mode → vertical bar
let &t_SI = "\e[6 q"
" Normal mode → block
let &t_EI = "\e[2 q"
" Replace mode → block
let &t_SR = "\e[2 q"
"hightlight the cursorline 
set cursorline
hi CursorLine cterm=none ctermbg=DarkMagenta ctermfg=254
"set nocursorcolumn
set incsearch
set hlsearch
"set ignorecast
"highlight Search ctermbg=gray ctermfg=NONE "------need to change color

" Show the sign column when vim-gitgutter is installed and enabled.
if exists(':GitGutterEnable') == 2 && get(g:, 'gitgutter_enabled', 1)
  set signcolumn=yes
endif
" Enable ctags/cscope navigation settings when Tagbar is installed. LSP may still
" be a better replacement depending on the project language and tooling.
if exists(':TagbarToggle') == 2
  set tags+=tags;
  set cscopetag
  set csto=0
  set cscopeverbose
  set wildignore+=tags
endif
set relativenumber
set number

"Tab relative bindings
map L <ESC>:tabnext<CR>
map H <ESC>:tabprev<CR>
map <C-t>n <ESC>:Texplore <bar><CR>
nmap dir  <ESC>:Explore<CR>
nmap sdir <ESC>:Sexplore<CR>
nmap vdir <ESC>:Vexplore<CR>
nmap <leader>T  <ESC>:tabnew<CR>:Explore<CR>

"set autoindent/smartindent/cindent
