"we can use vim-plug to replace Vundle!!
"set nocompatible              " be iMproved, required
"filetype off                  " required

" Vundle setting
let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
  echo "Installing Vundle.."
  echo ""
  silent !mkdir -p ~/.vim/bundle
  silent !git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/vundle
  let iCanHazVundle=0
endif
filetype off                  " required

if iCanHazVundle == 0
  " first-time setup, run PluginInstall automatically
  autocmd VimEnter * PluginInstall
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" ========== Plugin Setting ==========
Plugin 'lifepillar/vim-solarized8'
if empty(globpath(&runtimepath, 'colors/solarized8_flat.vim'))
  echohl ErrorMsg
  echom "Missing colorscheme solarized8_flat. Try running: vim -Nu ~/.vimrc -n '+PluginInstall' '+qall'"
  echohl None
endif
colorscheme solarized8_flat

Plugin 'itchyny/lightline.vim'
let g:lightline = {
      \ 'colorscheme': 'PaperColor',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'modified', 'filename' ] ],
      \ },
      \ 'mode_map': {
        \ 'n' : 'N',
        \ 'i' : 'I',
        \ 'R' : 'R',
        \ 'v' : 'V',
        \ 'V' : 'VL',
        \ "\<C-v>": 'VB',
        \ 'c' : 'C',
        \ 's' : 'S',
        \ 'S' : 'SL',
        \ "\<C-s>": 'SB',
        \ 't': 'T',
        \ },
      \ }
"Plugin 'mbbill/undotree'
"Plugin 'scrooloose/nerdtree' "nerdtree can somewhat be replaced by :h netrw
"Plugin 'vim-airline/vim-airline' "can be replaced by customized :h statusline

"Plugin 'dhruvasagar/vim-table-mode' "draw a good table
"Plugin 'hari-rangarajan/cctree'  "call tree, maybe YCM is sufficient
"Plugin 'mileszs/ack.vim'  "replace ack.vim by setting :h grepprg
"Plugin 'scrooloose/nerdcommenter'  "multi line comment tool
"Plugin 'SirVer/ultisnips'  "snippet driver, we can use vim-snippets with it.

filetype plugin indent on
" ========== Plugin Setting End ==========

set listchars=tab:>-,trail:-
" Use true color if supported, otherwise fall back to 256 colors
if exists('+termguicolors') && (has('nvim') || &term =~ 'xterm\|screen\|tmux')
  set termguicolors
else
  set t_Co=256
endif
set background=dark
set guifont=monospace\ 12

set backspace=indent,eol,start

" Show uncompleted command in the status line
set showcmd
set history=100

" Keep a statusline available if needed, though the filename is already shown on the tabline.
" set laststatus=2
set updatetime=250

set wrap
set linebreak

set matchpairs+=<:>
set mouse=n
set splitbelow

" Insert mode → vertical bar
let &t_SI = "\e[6 q"
" Normal mode → block
let &t_EI = "\e[2 q"
" Replace mode → block
let &t_SR = "\e[2 q"
"hightlight the cursorline 
set cursorline
hi CursorLine cterm=none ctermbg=DarkMagenta ctermfg=254
"set nocursorcolumn
set incsearch
set hlsearch
"set ignorecast
"highlight Search ctermbg=gray ctermfg=NONE "------need to change color

set relativenumber
set number

"Tab relative bindings
map L <ESC>:tabnext<CR>
map H <ESC>:tabprev<CR>
map <C-t>n <ESC>:Texplore <bar><CR>
nmap dir  <ESC>:Explore<CR>
nmap sdir <ESC>:Sexplore<CR>
nmap vdir <ESC>:Vexplore<CR>
nmap <leader>T  <ESC>:tabnew<CR>:Explore<CR>

"set autoindent/smartindent/cindent
